force-app/main/default/objects/Raw_Material__c/Raw_Material__c.object-meta.xml
<CustomObject>
    <label>Raw Material</label>
    <nameField>
        <label>Raw Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raw Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Raw_Material__c/fields/Low_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Low_Threshold__c</fullName>
    <label>Low Threshold</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Raw_Material__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Colorant</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Mould</fullName>
            </value>
            <value>
                <fullName>Misc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public with sharing class TestDataFactory {

    public static List<Raw_Material__c> rawMaterialsList(Integer num) {
        List<Raw_Material__c> rms = new List<Raw_Material__c>();

        for(Integer i = 0; i < num; i++) {
            String testName = 'test rm' + i;
            Raw_Material__c rm = new Raw_Material__c(Name=testName, Low_Threshold__c=100, Type__c='Colorant');
            rms.add(rm);
        }

        return rms;
    }
}